const stripeRequirements: any = {
  business_type: 'Account type',
  'business_profile.url': 'Website URL',
  'individual.first_name': 'First Name',
  'individual.last_name': 'Last Name',
  'individual.dob.day': 'Date of Birth',
  'individual.address.line1': 'Address Line 1',
  'individual.address.postal_code': 'Postal Code',
  'individual.address.city': 'City',
  'individual.address.state': 'State',
  'individual.email': 'Email Address',
  'individual.phone': 'Phone Number',
  'individual.ssn_last_4': 'Social Security Number',
  'individual.id_number': "Tax Document's ID",
  'individual.verification.document': 'Identity Verification Document',
  'company.name': 'Company Name',
  'company.address.line1': 'Company Address Line 1',
  'company.address.postal_code': 'Company Postal Code',
  'company.address.city': 'Company City',
  'company.address.state': 'Company State',
  'company.phone': 'Company Phone Number',
  'company.owners_provided': "Company Owner's details",
  'company.tax_id': 'Tax Documents',
  'representative.first_name': "Company Representative's First Name",
  'representative.last_name': "Company Representative's Last Name",
  'representative.dob.day': "Company Representative's Date of Birth",
  'representative.address.line1': "Company Representative's Address Line 1",
  'representative.address.postal_code': "Company Representative's Postal Code",
  'representative.address.city': "Company Representative's City",
  'representative.address.state': "Company Representative's State",
  'representative.email': "Company Representative's Email Address",
  'representative.phone': "Company Representative's Phone Number",
  'representative.ssn_last_4':
    "Company Representative's Social Security Number",
  'representative.relationship.title':
    "Company Representative's relation title",
  'representative.relationship.executive':
    "Company Representative's relation executive",
  'owners.first_name': "Company Owner's First Name",
  'owners.last_name': "Company Owner's Last Name",
  'owners.email': "Company Owner's Email Address",
  'tos_acceptance.date': 'Terms & Conditions Acceptance',
}
const excludedRequirementsForDisplay = [
  'tos_acceptance.ip',
  'external_account',
  'individual.dob.year',
  'individual.dob.month',
  'representative.dob.year',
  'representative.dob.month',
  'business_profile.mcc',
]

export { stripeRequirements, excludedRequirementsForDisplay }
